export const issueTypes = ["Road Damage", "Garbage", "Street Light", "Water Leak", "Drainage", "Public Safety", "Other"];

export const languages = [
  { code: "en", label: "English" },
  { code: "hi", label: "हिन्दी" },
  { code: "te", label: "తెలుగు" },
];

export const translations = {
  en: {
    feed: "Civic Feed",
    report: "Report",
    track: "Track",
    title: "CivicEye AI",
    home_title: "Clean City, Smart City",
    home_subtitle: "Your AI-powered bridge to city departments. Report issues in seconds.",
    start_btn: "Start a report",
    issue_type: "Issue type",
    issue_title: "Title",
    description: "Description",
    name: "Name",
    phone: "Phone",
    optional: "Optional",
    submit: "Submit complaint",
    routing: "Routing...",
    voice_note: "Voice note",
    voice_hint: "Optional voice context",
    listening: "Listening...",
    processing: "Analyzing audio...",
    attached: "Voice note attached",
    location: "Address or landmark",
    demo_loc: "Use demo location",
    success: "Success!",
    ticket_ready: "Your complaint has been routed.",
    ticket_id: "Ticket ID",
    track_btn: "Track status",
    new_btn: "Report another",
  },
  hi: {
    feed: "नागरिक फीड",
    report: "रिपोर्ट",
    track: "ट्रैक करें",
    title: "सिविकआई AI",
    home_title: "स्वच्छ शहर, स्मार्ट शहर",
    home_subtitle: "शहर के विभागों के लिए आपका AI-आधारित सेतु। सेकंडों में रिपोर्ट करें।",
    start_btn: "रिपोर्ट शुरू करें",
    issue_type: "समस्या का प्रकार",
    issue_title: "शीर्षक",
    description: "विवरण",
    name: "नाम",
    phone: "फोन",
    optional: "वैकल्पिक",
    submit: "शिकायत दर्ज करें",
    routing: "राउटिंग...",
    voice_note: "वॉयस नोट",
    voice_hint: "वैकल्पिक वॉयस संदर्भ",
    listening: "सुन रहे हैं...",
    processing: "ऑडियो विश्लेषण...",
    attached: "वॉयस नोट जुड़ा",
    location: "पता या लैंडमार्क",
    demo_loc: "डेमो लोकेशन का उपयोग करें",
    success: "सफलता!",
    ticket_ready: "आपकी शिकायत भेज दी गई है।",
    ticket_id: "टिकट आईडी",
    track_btn: "स्थिति ट्रैक करें",
    new_btn: "एक और रिपोर्ट करें",
  },
  te: {
    feed: "పౌర ఫీడ్",
    report: "నివేదించండి",
    track: "ట్రాక్ చేయండి",
    title: "సివిక్ ఐ AI",
    home_title: "శుభ్రమైన నగరం, స్మార్ట్ నగరం",
    home_subtitle: "నగర విభాగాలకు మీ AI-ఆధారిత వంతెన. సెకన్లలో నివేదించండి.",
    start_btn: "నివేదిక ప్రారంభించండి",
    issue_type: "సమస్య రకం",
    issue_title: "శీర్షిక",
    description: "వివరణ",
    name: "పేరు",
    phone: "ఫోన్",
    optional: "ఐచ్ఛికం",
    submit: "ఫిర్యాదు చేయండి",
    routing: "పంపుతోంది...",
    voice_note: "వాయిస్ నోట్",
    voice_hint: "ఐచ్ఛిక వాయిస్ సందర్భం",
    listening: "వింటున్నాము...",
    processing: "ఆడియో విశ్లేషణ...",
    attached: "వాయిస్ నోట్ జతచేయబడింది",
    location: "చిరునామా లేదా ల్యాండ్‌మార్క్",
    demo_loc: "డెమో స్థానాన్ని ఉపయోగించండి",
    success: "విజయం!",
    ticket_ready: "మీ ఫిర్యాదు పంపబడింది.",
    ticket_id: "టికెట్ ఐడి",
    track_btn: "స్థితిని ట్రాక్ చేయండి",
    new_btn: "మరొకటి నివేదించండి",
  }
};

